### ISSUE TITLE
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 571

### ISSUE THREAD

**Issue by avlap** [emuse/qmidiarp#12]
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 571

$ qmidiarp -v
 QMidiArp 0.6.5

Arch Linux

**Comment by emuse** [comment]
This isn't enough information.

- Please describe steps you did to produce this crash.

- Is this a package version or self-built from git?

- If it is a package version can you try to pull the latest git version and do
autoreconf -i
./configure --prefix=/usr
make

and try again?

Thanks

**Comment by avlap** [comment]
Git version works.

The package I was using is from Arch packages, default in Arch Linux.
