### ISSUE TITLE
Midi channel is not picked up

### ISSUE THREAD

**Issue by tiomja** [emuse/qmidiarp#13]
This is probably a handling error on my side but I wanted to report it anyway in desperate search of a solution.

In a simple setup with QMidiArp and Carla if I connect one SEQ1 to a Synth on OUT1/CHANNEL1 and another SEQ2 to OUT2/CHANNEL1 everything works as expected. But if I add a third synth on OUT2/CHANNEL1 it picks up the sequence from SEQ2. So far this is expected.

I tried to fix this by assigning the synth Midi CHANNEL 2 in Carla-GUI and setting it in QMidiArp on SEQ3 to CHANNEL2 as well but this seems to have no effect. Same output, same input on all connected devices. What am I missing? Or is this a bug? Thanks for any help as apart from that I really appreciate this tool.....

**Comment by emuse** [comment]
Hi Marcus,

thanks for your feedback, and sorry you're having trouble with this.
If I understand right you say setting the output channel to another one doesn't affect the synth's behaviour, which seems to receive on all channels?
I beleive the MIDI channels of the events sent by QMidiArp are correct. You can check the output events by connecting a MIDI monitor (either another instance of QMidiarp, or QMidiRoute or other...) to QMidiArp.

Which Synth are you using together with QMidiArp? Could you try with a standalone synth that allows setting the receive channel, for instance ZynAddSubFX ?

Best
Frank

**Comment by tiomja** [comment]
I figured it out. Of course qmidiarp is fine. I didn't know about MIDI filtering (it's not obvious) which can be achieved within Carla by loading a MIDI-Filter Plugin.
