### ISSUE TITLE
QMidiArp (Seq) gui doesn't open in BespokeSynth

### ISSUE THREAD

**Issue by sjomae** [emuse/qmidiarp#14]
BespokeSynth, latest git
Qmidiarp 0.6.6

**Comment by emuse** [comment]
Do you have suil installed on your system? Which version?

**Comment by sjomae** [comment]
suil 0.10.18-1

**Comment by emuse** [comment]
I maybe wrong but from the azure-pipelines.yml in Bespoke I think they don't build with libsuil necessary to manage the qt5 GUI. I've not been able to run Bespoke here (although it builds perfectly fine), so I cannot test.

**Comment by sjomae** [comment]
The binary should be in:
BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/

Try to run it from there? ./BespokeSynth

**Comment by emuse** [comment]
please check if the last commit fixes this issue with Bespoke

**Comment by sjomae** [comment]
There is a gui now. merci

**Comment by emuse** [comment]
Great. I'm closing the issue
