### ISSUE TITLE
QmidiArp crashes when trying to create LFO or Sequencer

### ISSUE THREAD

**Issue by JRSV** [emuse/qmidiarp#4]
In fedora 31, running Qmidiarp 0.6.5 I can only create arpeggiators, if I try to create LFO or a sequencer the program crashes.

**Comment by JRSV** [comment]
WHen running from the terminal I get this message qhen I produce the crash
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = Sample; _Alloc = std::allocator<Sample>; std::vector<_Tp, _Alloc>::reference = Sample&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)

**Comment by emuse** [comment]
OK thanks, I can guess what happens but not why for now. Two questions :
Is this upon add new seq/lfo with qmidiarp stopped and not connected to 
jack transport?

Does this also happen when you run the self built qmidiarp?
Frank

**Comment by JRSV** [comment]
so for your first question,
Is this upon add new seq/lfo with qmidiarp stopped and not connected to jack transport?
yes, fresh boot, with a qmidiarp empty, I can only crate the arpeggiator, any other option crashes. it is not connected to jacktransport and stopped from playback.

self built you mean a downloaded version of qmidiarp, yes, I could not compile myself becasue I ran into othe rproblems
