### ISSUE TITLE
QMidiArp Seq LV2 plugin doesn't sync with host (qtractor)

### ISSUE THREAD

**Issue by tcrass** [emuse/qmidiarp#7]
Hi,

neither version 0.6.5-1 (as provided by Debian Buster) nor a freshly compiled install (commit 85c472a) of qmidiarp's sequencer module syncs with qtractor (0.9.21 AppImage) when the "Sync with Host" checkbox is ticked. Actually, nothing happens at all, no matter whether qtractor is playing or not or if I send notes from a keyboard; the sequencer's progress indicator doesn't move, and no note events are generated. When running free (i.e. "Sync with Host" checkbox un-ticked), the sequencer runs fine, picks up input notes and gererates events.

Cheers --

    Torsten

**Comment by emuse** [comment]
Hi,

I just checked again, and the qmidiarp plugins' transport works just fine with qtractor here (Qtractor 0.9.12, so I'd expect them to work with the newest version, too). 

They do work with jalv.qt5, jalv.gtk and Ardour 5 here, too, including transport.

As to Ardour, you are probably aware that ardour disapproves non-statically linked (self-contained) plugin GUIs (there is lots of discussion on that topic out there), and unfortunately qmidiarp falls into that category. 

I had checked with Carla (2.0) once and it worked, too, but I cannot tell what the current status is. 

So there's at least two different issues in your case, one with qtractor and transport and probably others with the suil library and I don't know about carla. 

For the transport issue, you may check whether this works when qmidiarp is in standalone mode (qmidiarp app) with the jack transport button checked ?

Best
Frank

**Comment by tcrass** [comment]
> I just checked again, and the qmidiarp plugins' transport works just fine with qtractor here (Qtractor 0.9.12, so I'd expect them to work with the newest version, too).
> For the transport issue, you may check whether this works when qmidiarp is in standalone mode (qmidiarp app) with the jack transport button checked ?

OK, my bad... It did work once I had set qtractor to transport master mode (wasn't aware that I had to), now the seq syncs just fine both stand-alone and as plugin! :)

> As to Ardour, you are probably aware that ardour disapproves non-statically linked (self-contained) plugin GUIs (there is lots of discussion on that topic out there), and unfortunately qmidiarp falls into that category.

No, I wasn't... Still kinda newbie in this area.

> So there's at least two different issues in your case, one with qtractor and transport and probably others with the suil library and I don't know about carla.

I already opened another ticket (https://github.com/emuse/qmidiarp/issues/8) for the crashing issues, but this one can now be closed, I guess.

(Thanks a lot for spending your Saturday with looking into my QMidiArp issues...! :)

Cheers --

    Torsten
